import type {
  CookieCard,
  ItemCard,
  TrapCard,
  StageCard,
  Pack,
} from "../../types/card.type";

const ST2_COOKIE_CARDS: CookieCard[] = [
  {
    code: "ST2-001",
    name: "괴도맛 쿠키",
    type: "cookie",
    color: "Y",
    level: 3,
    rarity: ["SR"],
    pack: ["ST2"],
  },
  {
    code: "ST2-002",
    name: "딸기맛 쿠키",
    type: "cookie",
    color: "Y",
    level: 1,
    rarity: ["C"],
    pack: ["ST2"],
  },
  {
    code: "ST2-003",
    name: "마법사맛 쿠키",
    type: "cookie",
    color: "Y",
    level: 3,
    rarity: ["C"],
    pack: ["ST2"],
  },
  {
    code: "ST2-004",
    name: "마카롱맛 쿠키",
    type: "cookie",
    color: "Y",
    level: 2,
    rarity: ["U"],
    pack: ["ST2"],
  },
  {
    code: "ST2-005",
    name: "머스터드맛 쿠키",
    type: "cookie",
    color: "Y",
    level: 1,
    rarity: ["C"],
    pack: ["ST2"],
  },
  {
    code: "ST2-006",
    name: "명량한 쿠키",
    type: "cookie",
    color: "Y",
    level: 2,
    rarity: ["C"],
    pack: ["ST2"],
  },
  {
    code: "ST2-007",
    name: "밤톨맛 쿠키",
    type: "cookie",
    color: "Y",
    level: 1,
    rarity: ["C"],
    pack: ["ST2"],
  },
  {
    code: "ST2-008",
    name: "에클레어맛 쿠키",
    type: "cookie",
    color: "Y",
    level: 3,
    rarity: ["SR"],
    pack: ["ST2"],
  },
  {
    code: "ST2-009",
    name: "용감한 쿠키",
    type: "cookie",
    color: "Y",
    level: 1,
    rarity: ["C"],
    pack: ["ST2"],
  },
  {
    code: "ST2-010",
    name: "자색고구마맛 쿠키",
    type: "cookie",
    color: "Y",
    level: 3,
    rarity: ["U"],
    pack: ["ST2"],
  },
  {
    code: "ST2-011",
    name: "체리맛 쿠키",
    type: "cookie",
    color: "Y",
    level: 2,
    rarity: ["C"],
    pack: ["ST2"],
  },
  {
    code: "ST2-012",
    name: "치어리더맛 쿠키",
    type: "cookie",
    color: "Y",
    level: 2,
    rarity: ["C"],
    pack: ["ST2"],
  },
  {
    code: "ST2-013",
    name: "치즈케이크맛 쿠키",
    type: "cookie",
    color: "Y",
    level: 2,
    rarity: ["U"],
    pack: ["ST2"],
  },
  {
    code: "ST2-014",
    name: "커드터드 3세맛 쿠키",
    type: "cookie",
    color: "Y",
    level: 3,
    rarity: ["U"],
    pack: ["ST2"],
  },
  {
    code: "ST2-015",
    name: "히어로맛 쿠키",
    type: "cookie",
    color: "Y",
    level: 2,
    rarity: ["C"],
    pack: ["ST2"],
  },
];

const ST2_ITEM_CARDS: ItemCard[] = [
  {
    code: "ST2-016",
    name: "고장난 흑당 드라이버",
    type: "item",
    color: "Y",
    rarity: ["U"],
    pack: ["ST2"],
  },
  {
    code: "ST2-017",
    name: "리버스 타이머",
    type: "item",
    color: "Y",
    rarity: ["U"],
    pack: ["ST2"],
  },
  {
    code: "ST2-018",
    name: "시간 여행 티켓",
    type: "item",
    color: "Y",
    rarity: ["U"],
    pack: ["ST2"],
  },
  {
    code: "ST2-019",
    name: "영양 가득 꿀 폭탄",
    type: "item",
    color: "Y",
    rarity: ["U"],
    pack: ["ST2"],
  },
];

const ST2_TRAP_CARDS: TrapCard[] = [
  {
    code: "ST2-020",
    name: "강철 태엽 방패",
    type: "trap",
    color: "Y",
    rarity: ["U"],
    pack: ["ST2"],
  },
  {
    code: "ST2-021",
    name: "프레첼 덫",
    type: "trap",
    color: "Y",
    rarity: ["U"],
    pack: ["ST2"],
  },
];

const ST2_STAGE_CARDS: StageCard[] = [
  {
    code: "ST2-022",
    name: "시간 효율 관리부",
    type: "stage",
    color: "Y",
    rarity: ["U"],
    pack: ["ST2"],
  },
];

const ST2_CARDS: Pack = {
  cookie: ST2_COOKIE_CARDS,
  item: ST2_ITEM_CARDS,
  trap: ST2_TRAP_CARDS,
  stage: ST2_STAGE_CARDS,
};

export default ST2_CARDS;
