import type {
  CookieCard,
  ItemCard,
  TrapCard,
  StageCard,
  Pack,
} from "../../types/card.type";

const ST3_COOKIE_CARDS: CookieCard[] = [
  {
    code: "ST3-001",
    name: "근육맛 쿠키",
    type: "cookie",
    color: "G",
    level: 2,
    rarity: ["C"],
    pack: ["ST3"],
  },
  {
    code: "ST3-002",
    name: "딸기크레페맛 쿠키",
    type: "cookie",
    color: "G",
    level: 3,
    rarity: ["SR"],
    pack: ["ST3"],
  },
  {
    code: "ST3-003",
    name: "명량한 쿠키",
    type: "cookie",
    color: "G",
    level: 2,
    rarity: ["C"],
    pack: ["ST3"],
  },
  {
    code: "ST3-004",
    name: "뱀파이어맛 쿠키",
    type: "cookie",
    color: "G",
    level: 3,
    rarity: ["U"],
    pack: ["ST3"],
  },
  {
    code: "ST3-005",
    name: "블랙베리맛 쿠키",
    type: "cookie",
    color: "G",
    level: 2,
    rarity: ["C"],
    pack: ["ST3"],
  },
  {
    code: "ST3-006",
    name: "비트맛 쿠키",
    type: "cookie",
    color: "G",
    level: 2,
    rarity: ["U"],
    pack: ["ST3"],
  },
  {
    code: "ST3-007",
    name: "스파클링맛 쿠키",
    type: "cookie",
    color: "G",
    level: 3,
    rarity: ["U"],
    pack: ["ST3"],
  },
  {
    code: "ST3-008",
    name: "시금치맛 쿠키",
    type: "cookie",
    color: "G",
    level: 1,
    rarity: ["C"],
    pack: ["ST3"],
  },
  {
    code: "ST3-009",
    name: "아보카도맛 쿠키",
    type: "cookie",
    color: "G",
    level: 2,
    rarity: ["C"],
    pack: ["ST3"],
  },
  {
    code: "ST3-010",
    name: "알로에맛 쿠키",
    type: "cookie",
    color: "G",
    level: 2,
    rarity: ["SR"],
    pack: ["ST3"],
  },
  {
    code: "ST3-011",
    name: "양파맛 쿠키",
    type: "cookie",
    color: "G",
    level: 2,
    rarity: ["C"],
    pack: ["ST3"],
  },
  {
    code: "ST3-012",
    name: "용감한 쿠키",
    type: "cookie",
    color: "G",
    level: 1,
    rarity: ["C"],
    pack: ["ST3"],
  },
  {
    code: "ST3-013",
    name: "용사맛 쿠키",
    type: "cookie",
    color: "G",
    level: 1,
    rarity: ["C"],
    pack: ["ST3"],
  },
  {
    code: "ST3-014",
    name: "천사맛 쿠키",
    type: "cookie",
    color: "G",
    level: 2,
    rarity: ["C"],
    pack: ["ST3"],
  },
  {
    code: "ST3-015",
    name: "칠리맛 쿠키",
    type: "cookie",
    color: "G",
    level: 2,
    rarity: ["U"],
    pack: ["ST3"],
  },
];

const ST3_ITEM_CARDS: ItemCard[] = [
  {
    code: "ST3-016",
    name: "고대 치유사의 보살핌",
    type: "item",
    color: "G",
    rarity: ["U"],
    pack: ["ST3"],
  },
  {
    code: "ST3-017",
    name: "여행 가시 덩쿨",
    type: "item",
    color: "G",
    rarity: ["U"],
    pack: ["ST3"],
  },
  {
    code: "ST3-018",
    name: "생명력 듬뿍 담은 파슬리 차",
    type: "item",
    color: "G",
    rarity: ["U"],
    pack: ["ST3"],
  },
];

const ST3_TRAP_CARDS: TrapCard[] = [
  {
    code: "ST3-019",
    name: "백만 번 휘저은 휘핑크림",
    type: "trap",
    color: "G",
    rarity: ["U"],
    pack: ["ST3"],
  },
  {
    code: "ST3-020",
    name: "신성한 빛의 결계",
    type: "trap",
    color: "G",
    rarity: ["U"],
    pack: ["ST3"],
  },
  {
    code: "ST3-021",
    name: "뿔피리의 부름",
    type: "trap",
    color: "G",
    rarity: ["U"],
    pack: ["ST3"],
  },
];

const ST3_STAGE_CARDS: StageCard[] = [
  {
    code: "ST3-022",
    name: "수호목의 은혜",
    type: "stage",
    color: "G",
    rarity: ["U"],
    pack: ["ST3"],
  },
];

const ST3_CARDS: Pack = {
  cookie: ST3_COOKIE_CARDS,
  item: ST3_ITEM_CARDS,
  trap: ST3_TRAP_CARDS,
  stage: ST3_STAGE_CARDS,
};

export default ST3_CARDS;
