import type {
  CookieCard,
  ItemCard,
  TrapCard,
  StageCard,
  Pack,
} from "../../types/card.type";

const BS1_COOKIE_CARDS: CookieCard[] = [
  {
    code: "BS1-001",
    name: "고블린맛 쿠키",
    type: "cookie",
    color: "R",
    level: 1,
    rarity: ["C"],
    pack: ["BS1"],
  },
  {
    code: "BS1-002",
    name: "구미호맛 쿠키",
    type: "cookie",
    color: "R",
    level: 3,
    rarity: ["R", "SEC"],
    pack: ["BS1"],
  },
  {
    code: "BS1-003",
    name: "다크초코 쿠키",
    type: "cookie",
    color: "R",
    level: 2,
    rarity: ["SR", "SSR"],
    pack: ["BS1"],
  },
  {
    code: "BS1-004",
    name: "라일락맛 쿠키",
    type: "cookie",
    color: "R",
    level: 1,
    rarity: ["U"],
    pack: ["BS1"],
  },
  {
    code: "BS1-005",
    name: "롤케이크맛 쿠키",
    type: "cookie",
    color: "R",
    level: 2,
    rarity: ["C"],
    pack: ["BS1"],
  },
  {
    code: "BS1-006",
    name: "마라맛 쿠키",
    type: "cookie",
    color: "R",
    level: 2,
    rarity: ["U"],
    pack: ["BS1"],
  },
  {
    code: "BS1-007",
    name: "메론빵맛 쿠키",
    type: "cookie",
    color: "R",
    level: 1,
    rarity: ["C"],
    pack: ["BS1"],
  },
  {
    code: "BS1-008",
    name: "석류맛 쿠키",
    type: "cookie",
    color: "R",
    level: 2,
    rarity: ["R", "SEC"],
    pack: ["BS1"],
  },
  {
    code: "BS1-009",
    name: "아포가토맛 쿠키",
    type: "cookie",
    color: "R",
    level: 1,
    rarity: ["R", "SEC"],
    pack: ["BS1"],
  },
  {
    code: "BS1-010",
    name: "악마맛 쿠키",
    type: "cookie",
    color: "R",
    level: 1,
    rarity: ["C"],
    pack: ["BS1"],
  },
  {
    code: "BS1-011",
    name: "앵두맛 쿠키",
    type: "cookie",
    color: "R",
    level: 1,
    rarity: ["C"],
    pack: ["BS1"],
  },
  {
    code: "BS1-012",
    name: "와일드베리맛 쿠키",
    type: "cookie",
    color: "R",
    level: 3,
    rarity: ["SR", "SSR"],
    pack: ["BS1"],
  },
  {
    code: "BS1-013",
    name: "용감한 쿠키",
    type: "cookie",
    color: "R",
    level: 1,
    rarity: ["C"],
    pack: ["BS1"],
  },
  {
    code: "BS1-014",
    name: "용감한 쿠키",
    type: "cookie",
    color: "R",
    level: 1,
    rarity: ["UR", "SUR"],
    pack: ["BS1"],
  },
  {
    code: "BS1-015",
    name: "장미맛 쿠키",
    type: "cookie",
    color: "R",
    level: 3,
    rarity: ["U"],
    pack: ["BS1"],
  },
  {
    code: "BS1-016",
    name: "초코볼맛 쿠키",
    type: "cookie",
    color: "R",
    level: 2,
    rarity: ["C"],
    pack: ["BS1"],
  },
  {
    code: "BS1-017",
    name: "크루아상맛 쿠키",
    type: "cookie",
    color: "R",
    level: 1,
    rarity: ["SR", "SSR"],
    pack: ["BS1"],
  },
  {
    code: "BS1-018",
    name: "팝콘맛 쿠키",
    type: "cookie",
    color: "R",
    level: 1,
    rarity: ["U"],
    pack: ["BS1"],
  },
  {
    code: "BS1-019",
    name: "호두맛 쿠키",
    type: "cookie",
    color: "R",
    level: 3,
    rarity: ["C"],
    pack: ["BS1"],
  },
  {
    code: "BS1-020",
    name: "홍고추맛 쿠키",
    type: "cookie",
    color: "R",
    level: 3,
    rarity: ["C"],
    pack: ["BS1"],
  },
  {
    code: "BS1-021",
    name: "휘핑크림맛 쿠키",
    type: "cookie",
    color: "R",
    level: 2,
    rarity: ["C"],
    pack: ["BS1"],
  },
  {
    code: "BS1-027",
    name: "구슬아이스맛 쿠키",
    type: "cookie",
    color: "Y",
    level: 2,
    rarity: ["C"],
    pack: ["BS1"],
  },
  {
    code: "BS1-028",
    name: "라떼맛 쿠키",
    type: "cookie",
    color: "Y",
    level: 3,
    rarity: ["SR", "SSR"],
    pack: ["BS1"],
  },
  {
    code: "BS1-029",
    name: "라임맛 쿠키",
    type: "cookie",
    color: "Y",
    level: 1,
    rarity: ["U"],
    pack: ["BS1"],
  },
  {
    code: "BS1-030",
    name: "락스타맛 쿠키",
    type: "cookie",
    color: "Y",
    level: 2,
    rarity: ["C"],
    pack: ["BS1"],
  },
  {
    code: "BS1-031",
    name: "마시멜로맛 쿠키",
    type: "cookie",
    color: "Y",
    level: 1,
    rarity: ["R", "SEC"],
    pack: ["BS1"],
  },
  {
    code: "BS1-032",
    name: "바나나맛 쿠키",
    type: "cookie",
    color: "Y",
    level: 1,
    rarity: ["C"],
    pack: ["BS1"],
  },
  {
    code: "BS1-033",
    name: "사이보그맛 쿠키",
    type: "cookie",
    color: "Y",
    level: 1,
    rarity: ["R", "SEC"],
    pack: ["BS1"],
  },
  {
    code: "BS1-034",
    name: "샌드위치맛 쿠키",
    type: "cookie",
    color: "Y",
    level: 1,
    rarity: ["C"],
    pack: ["BS1"],
  },
  {
    code: "BS1-035",
    name: "솜사탕맛 쿠키",
    type: "cookie",
    color: "Y",
    level: 2,
    rarity: ["U"],
    pack: ["BS1"],
  },
  {
    code: "BS1-036",
    name: "스네이크후르츠맛 쿠키",
    type: "cookie",
    color: "Y",
    level: 2,
    rarity: ["SR", "SSR"],
    pack: ["BS1"],
  },
  {
    code: "BS1-037",
    name: "시간지기 쿠키",
    type: "cookie",
    color: "Y",
    level: 3,
    rarity: ["UR", "SUR"],
    pack: ["BS1"],
  },
  {
    code: "BS1-038",
    name: "시나몬맛 쿠키",
    type: "cookie",
    color: "Y",
    level: 1,
    rarity: ["U"],
    pack: ["BS1"],
  },
  {
    code: "BS1-039",
    name: "아몬드맛 쿠키",
    type: "cookie",
    color: "Y",
    level: 2,
    rarity: ["U"],
    pack: ["BS1"],
  },
  {
    code: "BS1-040",
    name: "얼그레이맛 쿠키",
    type: "cookie",
    color: "Y",
    level: 3,
    rarity: ["R", "SEC"],
    pack: ["BS1"],
  },
  {
    code: "BS1-041",
    name: "오렌지맛 쿠키",
    type: "cookie",
    color: "Y",
    level: 1,
    rarity: ["C"],
    pack: ["BS1"],
  },
  {
    code: "BS1-042",
    name: "자몽맛 쿠키",
    type: "cookie",
    color: "Y",
    level: 2,
    rarity: ["C"],
    pack: ["BS1"],
  },
  {
    code: "BS1-043",
    name: "치즈케이크맛 쿠키",
    type: "cookie",
    color: "Y",
    level: 2,
    rarity: ["C"],
    pack: ["BS1"],
  },
  {
    code: "BS1-044",
    name: "파프리카맛 쿠키",
    type: "cookie",
    color: "Y",
    level: 2,
    rarity: ["SR", "SSR"],
    pack: ["BS1"],
  },
  {
    code: "BS1-045",
    name: "폭죽맛 쿠키",
    type: "cookie",
    color: "Y",
    level: 3,
    rarity: ["C"],
    pack: ["BS1"],
  },
  {
    code: "BS1-046",
    name: "풋사과맛 쿠키",
    type: "cookie",
    color: "Y",
    level: 3,
    rarity: ["C"],
    pack: ["BS1"],
  },
  {
    code: "BS1-047",
    name: "피자맛 쿠키",
    type: "cookie",
    color: "Y",
    level: 3,
    rarity: ["C"],
    pack: ["BS1"],
  },
  {
    code: "BS1-053",
    name: "괴도맛 쿠키",
    type: "cookie",
    color: "G",
    level: 1,
    rarity: ["UR", "SUR"],
    pack: ["BS1"],
  },
  {
    code: "BS1-054",
    name: "난초맛 쿠키",
    type: "cookie",
    color: "G",
    level: 3,
    rarity: ["SR", "SSR"],
    pack: ["BS1"],
  },
  {
    code: "BS1-055",
    name: "단팥맛 쿠키",
    type: "cookie",
    color: "G",
    level: 2,
    rarity: ["U"],
    pack: ["BS1"],
  },
  {
    code: "BS1-056",
    name: "달토끼맛 쿠키",
    type: "cookie",
    color: "G",
    level: 2,
    rarity: ["SR", "SSR"],
    pack: ["BS1"],
  },
  {
    code: "BS1-057",
    name: "더덕꽃맛 쿠키",
    type: "cookie",
    color: "G",
    level: 1,
    rarity: ["C"],
    pack: ["BS1"],
  },
  {
    code: "BS1-058",
    name: "독버섯맛 쿠키",
    type: "cookie",
    color: "G",
    level: 2,
    rarity: ["C"],
    pack: ["BS1"],
  },
  {
    code: "BS1-059",
    name: "무화과맛 쿠키",
    type: "cookie",
    color: "G",
    level: 3,
    rarity: ["C"],
    pack: ["BS1"],
  },
  {
    code: "BS1-060",
    name: "버터베어맛 쿠키",
    type: "cookie",
    color: "G",
    level: 2,
    rarity: ["C"],
    pack: ["BS1"],
  },
  {
    code: "BS1-061",
    name: "복숭아맛 쿠키",
    type: "cookie",
    color: "G",
    level: 2,
    rarity: ["C"],
    pack: ["BS1"],
  },
  {
    code: "BS1-062",
    name: "실론나이트 쿠키",
    type: "cookie",
    color: "G",
    level: 1,
    rarity: ["R", "SEC"],
    pack: ["BS1"],
  },
  {
    code: "BS1-063",
    name: "예언자맛 쿠키",
    type: "cookie",
    color: "G",
    level: 1,
    rarity: ["C"],
    pack: ["BS1"],
  },
  {
    code: "BS1-064",
    name: "인삼맛 쿠키",
    type: "cookie",
    color: "G",
    level: 2,
    rarity: ["C"],
    pack: ["BS1"],
  },
  {
    code: "BS1-065",
    name: "자두맛 쿠키",
    type: "cookie",
    color: "G",
    level: 1,
    rarity: ["C"],
    pack: ["BS1"],
  },
  {
    code: "BS1-066",
    name: "지초맛 쿠키",
    type: "cookie",
    color: "G",
    level: 2,
    rarity: ["SR", "SSR"],
    pack: ["BS1"],
  },
  {
    code: "BS1-067",
    name: "츄러스맛 쿠키",
    type: "cookie",
    color: "G",
    level: 3,
    rarity: ["R", "SEC"],
    pack: ["BS1"],
  },
  {
    code: "BS1-068",
    name: "콜리플라워맛 쿠키",
    type: "cookie",
    color: "G",
    level: 2,
    rarity: ["C"],
    pack: ["BS1"],
  },
  {
    code: "BS1-069",
    name: "쿠키멀즈",
    type: "cookie",
    color: "G",
    level: 1,
    rarity: ["U"],
    pack: ["BS1"],
  },
  {
    code: "BS1-070",
    name: "키위맛 쿠키",
    type: "cookie",
    color: "G",
    level: 2,
    rarity: ["U"],
    pack: ["BS1"],
  },
  {
    code: "BS1-071",
    name: "펌킨파이맛 쿠키",
    type: "cookie",
    color: "G",
    level: 3,
    rarity: ["R", "SEC"],
    pack: ["BS1"],
  },
  {
    code: "BS1-072",
    name: "푸딩맛 쿠키",
    type: "cookie",
    color: "G",
    level: 3,
    rarity: ["C"],
    pack: ["BS1"],
  },
  {
    code: "BS1-073",
    name: "허브맛 쿠키",
    type: "cookie",
    color: "G",
    level: 2,
    rarity: ["U"],
    pack: ["BS1"],
  },
];

const BS1_ITEM_CARDS: ItemCard[] = [
  {
    code: "BS1-022",
    name: "거대한 체리 폭탄",
    type: "item",
    color: "R",
    rarity: ["R"],
    pack: ["BS1"],
  },
  {
    code: "BS1-023",
    name: "스파이시 파워 주스",
    type: "item",
    color: "R",
    rarity: ["U"],
    pack: ["BS1"],
  },
  {
    code: "BS1-048",
    name: "테이프 젤리 폼폼",
    type: "item",
    color: "Y",
    rarity: ["U"],
    pack: ["BS1"],
  },
  {
    code: "BS1-049",
    name: "트로피컬 슬러시",
    type: "item",
    color: "Y",
    rarity: ["R"],
    pack: ["BS1"],
  },
  {
    code: "BS1-074",
    name: "고대 숲의 행운석",
    type: "item",
    color: "G",
    rarity: ["U"],
    pack: ["BS1"],
  },
  {
    code: "BS1-075",
    name: "방랑자의 사과파이",
    type: "item",
    color: "G",
    rarity: ["R"],
    pack: ["BS1"],
  },
];

const BS1_TRAP_CARDS: TrapCard[] = [
  {
    code: "BS1-024",
    name: "파스타 스프링 슈즈",
    type: "trap",
    color: "R",
    rarity: ["U"],
    pack: ["BS1"],
  },
  {
    code: "BS1-025",
    name: "파인애플 헬멧",
    type: "trap",
    color: "R",
    rarity: ["U"],
    pack: ["BS1"],
  },
  {
    code: "BS1-050",
    name: "부서진 이정표",
    type: "trap",
    color: "Y",
    rarity: ["U"],
    pack: ["BS1"],
  },
  {
    code: "BS1-051",
    name: "활력 듬뿍 젤리바",
    type: "trap",
    color: "Y",
    rarity: ["U"],
    pack: ["BS1"],
  },
  {
    code: "BS1-076",
    name: "깜짝 쐐기돌",
    type: "trap",
    color: "G",
    rarity: ["U"],
    pack: ["BS1"],
  },
  {
    code: "BS1-077",
    name: "잼파이 구급상자",
    type: "trap",
    color: "G",
    rarity: ["U"],
    pack: ["BS1"],
  },
];

const BS1_STAGE_CARDS: StageCard[] = [
  {
    code: "BS1-026",
    name: "사막 속 오아시스",
    type: "stage",
    color: "R",
    rarity: ["U"],
    pack: ["BS1"],
  },
  {
    code: "BS1-052",
    name: "별사탕 오솔길",
    type: "stage",
    color: "Y",
    rarity: ["U"],
    pack: ["BS1"],
  },
  {
    code: "BS1-078",
    name: "되살아나는 고대 숲",
    type: "stage",
    color: "G",
    rarity: ["U"],
    pack: ["BS1"],
  },
];

export const BS1_REPACK_CODES = [
  "ST1-004",
  "ST1-012",
  "ST1-015",
  "ST2-002",
  "ST2-007",
  "ST2-014",
  "ST3-007",
  "ST3-013",
  "ST3-014",
];

const BS1_CARDS: Pack = {
  cookie: BS1_COOKIE_CARDS,
  item: BS1_ITEM_CARDS,
  trap: BS1_TRAP_CARDS,
  stage: BS1_STAGE_CARDS,
  repack: BS1_REPACK_CODES,
};

export default BS1_CARDS;
